/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import React, { useMemo } from 'react';


export default function RockParticles({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/4JtsRGNUvM01JPnp/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#63656b']} />
            <fog attach="fog" args={['#63656b', 0, 4500]} />
            <group {...props} dispose={null}>
                <scene name="Scene 1">
                    <spotLight
                        name="Warm"
                        castShadow
                        intensity={1.98}
                        angle={0.98}
                        penumbra={1}
                        decay={0}
                        distance={9698}
                        shadow-mapSize-width={2048}
                        shadow-mapSize-height={2048}
                        shadow-camera-fov={119.99999999999999}
                        shadow-camera-near={100}
                        shadow-camera-far={100000}
                        color="#f6f1ee"
                        position={[770.97, 911.89, 1712.59]}
                        rotation={[1.21, 0.12, -0.43]}
                        scale={1}
                    />
                    <PerspectiveCamera
                        name="Camera"
                        makeDefault={true}
                        far={100000}
                        near={70}
                        fov={45}
                        position={[0, 0, 1000]}
                        rotation={[0, 0, 0]}
                    />
                    <mesh
                        name="Line"
                        geometry={nodes.Line.geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-448, -320.03, -10]}
                        scale={[0.4, 0.75, 1]}
                    />
                    <group name="Follow" position={[0, 0, 60]} scale={1.09}>
                        <mesh
                            name="Sphere"
                            geometry={nodes.Sphere.geometry}
                            material={materials['Sphere Material']}
                            castShadow
                            receiveShadow
                            position={[-540, -210, 100]}
                        />
                    </group>
                    <group name="Follow " position={[-50.82, 37.36, 60]} rotation={[Math.PI / 2, 0, 0]} scale={0.32}>
                        <mesh
                            name="Sphere1"
                            geometry={nodes.Sphere1.geometry}
                            material={materials['Sphere1 Material']}
                            castShadow
                            receiveShadow
                            position={[780, 700, -760]}
                        />
                    </group>
                    <group name="Follow1" position={[0, 0, 67]} scale={0.45}>
                        <mesh
                            name="Sphere2"
                            geometry={nodes.Sphere2.geometry}
                            material={materials['Sphere2 Material']}
                            castShadow
                            receiveShadow
                            position={[-530, -20, 0]}
                        />
                    </group>
                    <group name="Follow2" scale={[0.67, 0.67, 0.59]}>
                        <mesh
                            name="Sphere3"
                            geometry={nodes.Sphere3.geometry}
                            material={materials['Sphere3 Material']}
                            castShadow
                            receiveShadow
                            position={[-370, 380, 245]}
                        />
                    </group>
                    <group name="Follow 1" position={[27.69, -56.12, 70.51]} scale={[1.28, 1.28, 1.13]}>
                        <mesh
                            name="Rectangle"
                            geometry={nodes.Rectangle.geometry}
                            material={materials['Rectangle Material']}
                            castShadow
                            receiveShadow
                            position={[-594.08, 116.39, -429.81]}
                            rotation={[0, 0.75, 0]}
                            scale={[0.96, 0.89, 0.27]}
                        />
                        <mesh
                            name="Sphere4"
                            geometry={nodes.Sphere4.geometry}
                            material={materials['Sphere4 Material']}
                            castShadow
                            receiveShadow
                            position={[-850, 100, -850]}
                            scale={2}
                        />
                    </group>
                    <group name="Follow3" scale={[1.73, 1.73, 1.52]}>
                        <mesh
                            name="Rectangle1"
                            geometry={nodes.Rectangle1.geometry}
                            material={materials['Rectangle1 Material']}
                            castShadow
                            receiveShadow
                            position={[184.86, 301.58, -725.18]}
                            scale={[0.67, 0.75, 0.2]}
                        />
                        <mesh
                            name="Sphere5"
                            geometry={nodes.Sphere5.geometry}
                            material={materials['Sphere5 Material']}
                            castShadow
                            receiveShadow
                            position={[156.57, 316.09, -1065.16]}
                            rotation={[0, 0, 0]}
                            scale={1.5}
                        />
                    </group>
                    <group name="Follow4" position={[-2.31, 0.88, 75.51]} scale={[1.73, 1.73, 1.52]}>
                        <mesh
                            name="Sphere6"
                            geometry={nodes.Sphere6.geometry}
                            material={materials['Sphere6 Material']}
                            castShadow
                            receiveShadow
                            position={[302, 0, 85.06]}
                            scale={0.8}
                        />
                    </group>
                    <group name="Follow5" position={[-2.31, 0.88, 75.51]} scale={[0.6, 0.6, 0.53]}>
                        <mesh
                            name="Sphere7"
                            geometry={nodes.Sphere7.geometry}
                            material={materials['Sphere7 Material']}
                            castShadow
                            receiveShadow
                            position={[310, 80, 130]}
                        />
                    </group>
                    <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
                </scene>
            </group>
        </>
    )
}
